### ISSUE TITLE
"Setting" values impact creation results

### ISSUE THREAD

**Issue by MichelV69** [MichelV69/fantasy-tavern-maker-tui#9]
### Enum
Downtown, Midtown, Uptown, Docks, Slums, Outskirts, Crossroads, Milehouse, Outpost, Wilderness

### CLI Option
`--setting="midtown"`

### Ideas
Tunable via YAML file?

```yaml
Slums:
    size: -1
    quality: -1
    patrons:
       commonfolk: +1
    redlight:
       count: +1
      dc: -1
```
